데이터 과학, ML 분야에서 자주 쓰이는 파이썬 라이브러리인 NumPy, Pandas, Matplotlib, TensorFlow, PyTorch, Scipy, scikit-learn 쓰다가 남겨보는 끄적끄적...기록

# Numpy

In [5]:
import numpy as np

In [9]:
# TODO: Divide each row by a vector element
data = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])
vector = np.array([1, 2, 3])

print(data)
print(data / vector)
print(vector)
print(vector.reshape(-1, 1))
print(data / vector.reshape(-1, 1))
print(data / vector.reshape(1, -1))

[[1 1 1]
 [2 2 2]
 [3 3 3]]
[[1.         0.5        0.33333333]
 [2.         1.         0.66666667]
 [3.         1.5        1.        ]]
[1 2 3]
[[1]
 [2]
 [3]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1.         0.5        0.33333333]
 [2.         1.         0.66666667]
 [3.         1.5        1.        ]]


- [출처: 스택오버플로우](https://stackoverflow.com/questions/19602187/numpy-divide-each-row-by-a-vector-element)
- 핵심: 각 행을 각 원소로 나누려면 size(3,)짜리 벡터를 (3,1)짜리 벡터로 reshape해야한다는 것!
  - size(3,)인 벡터로 나누면 size(1,3)으로 나눈 결과와 똑같아짐 => 이것은 각 열을 각 원소로 나눈 결과다!
  - +) 이런 조건을 충족하면 넘파이 연산 시 브로드캐스팅이 일어나서 (3,1) -> (3,3)으로 shape이 확장됨